spring:

  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
    gateway:
      server:
        webflux:
          routes[0]:
            id: car-service
            uri: lb://car-service
            predicates[0]: Path=/api/cars/**
          routes[1]:
            id: product-service
            uri: lb://product-service
            predicates[0]: Path=/api/products/**
          routes[2]:
            id: discovery-server
            uri: lb://discovery-server
            predicates[0]: Path=/eureka**
    discovery:
      locator:
        enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/finwise-realm
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE