spring:
  config:
    import: optional:configserver:http://config-server:9595
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/finwise-realm
